#!/bin/bash
set -e

export MALLOC_ARENA_MAX=2
REAL_BROWSER="$(cat /usr/local/share/orbit-browser-real)"

exec "$REAL_BROWSER" \
  --disable-dev-shm-usage \
  --disable-gpu \
  --disable-extensions \
  --disable-sync \
  --disable-background-networking \
  --disable-component-update \
  --disable-domain-reliability \
  --disable-features=BackForwardCache,MediaRouter,OptimizationHints,Translate,AutofillServerCommunication \
  --renderer-process-limit=1 \
  --process-per-site \
  --disk-cache-size=67108864 \
  --media-cache-size=33554432 \
  --js-flags=--max-old-space-size=256 \
  "$@"
